### ISSUE TITLE
Introduce options for datasets without dev set

### ISSUE THREAD

**Issue by isabelleaugenstein** [uclmr/jack#143]
If no dev set specified, offer options to:
- [ ] run training pipeline without dev set
- [ ] draw n random instances from training set for dev, which are then removed from training set
- [ ] draw n random instances from training set for dev, but keep them in training set

**Comment by pminervini** [comment]
I think the safest thing to do is to leave the splitting to the user (e.g. by using `sklearn`) - it will help keeping the framework "simple" (it's already quite messy)
