### ISSUE TITLE
get n most likely spans fastqa

### ISSUE THREAD

**Issue by Vict0rSch** [uclmr/jack#228]
I'm not sure how to get the fastqa_reader to output not only the most likely span (+ score + text), but rather the n most likely. 

As I understand it, it should be changed in the ModelModule `jtr/jtr/tasks/xqa/fastqa.py` to be fed into the OutputModule's `__call__` function (in `jtr/jtr/tasks/xqa/shared.py`)

It seems like `predicted_idx = tf.cast(tf.argmax(predicted_start_probs * predicted_end_probs, 1), tf.int32)` is defined in the purpose of returning solely the most likely span. 

Should I try and use a `top_k` instead of `argmax` or is there an easier way I'm not getting?

**Comment by dirkweissenborn** [comment]
for all ModularQA models (everything but FastQA) this is possible now with `reader.model_module.set_beam_size(k)`. After setting that the output module will provide the top k answers. For FastQA you would need to set the beam_size argument in the configuration. For trained models it is possible in the `reader_from_file` method (of `jack.readers.implementations`) to overwrite configuration arguments before creating the reader. `reader = reader_from_file(/path/to/fastqa_reader, beam_size=k)`
