### ISSUE TITLE
FastQA reader returns `(begin, end)` span instead of `(doc_id, begin, end)` as per documentation

### ISSUE THREAD

**Issue by undwie** [uclmr/jack#242]
This is just surfacing the underlying bigger issue of the readers supporting multiple support documents by interface, but probably not really by implementation. 

Possible fixes:
* don't allow multiple support documents for the time being (do we have readers that use this right now?)
* allow multiple supports, and have some simple default implementation (concat text) and some way of mapping the spans from the concat documents to document ids of the original docs.

**Comment by TimDettmers** [comment]
What is the current progress on this issue?
