### ISSUE TITLE
Clean-ups/refactoring/documentation for v0.1

### ISSUE THREAD

**Issue by dirkweissenborn** [uclmr/jack#257]
Basically make your (most important) code look nice!

- basic refactoring (clean-ups) 
- Documentation
- External & Internal / Markdown

Everyone please go through your code and add missing documentation and docstrings roughly following the [google comment style guidelines](https://google.github.io/styleguide/pyguide.html#Comments).

**Comment by TimDettmers** [comment]
This is a bit underspecified. Dirk already refactored quite a bit, and there is another issue already for fixing the documentation.
