### ISSUE TITLE
Check all notebooks

### ISSUE THREAD

**Issue by dirkweissenborn** [uclmr/jack#258]
Check Notebooks (test them, more documentation) 
- [ ] NYT
- [ ] Showcasing Jack
- [x] SNLI

**Comment by pminervini** [comment]
I'm on it - currently trying to fix https://github.com/uclmr/jack/blob/master/notebooks/Implementing_a_new_model.ipynb

**Comment by pminervini** [comment]
I'm getting an error at the following line at `SNLI.ipynb`:

```python
reader.output_module = MisclassificationOutputModule(interval=[0.0, 0.20], limit=10)
```

The error is `AttributeError: can't set attribute`: @dirkweissenborn can you fix it?

**Comment by riedelcastro** [comment]
On that note: do we really need a `MisclassificationOutputModule`? I think output modules should simply transform the model predictions to usable python Answer objects. Misclassification calculation etc. should happen outside of it. Maybe this is easier to fix just in that way?

**Comment by pminervini** [comment]
All notebooks should be fine now.
