### ISSUE TITLE
Downloadable Models for different datasets

### ISSUE THREAD

**Issue by dirkweissenborn** [uclmr/jack#261]
- [x] BiDAF
- [ ] SNLI: ESIM

**Comment by dirkweissenborn** [comment]
@pminervini the embeddings are not stored with the model anyways. What @riedelcastro suggested is to convert embeddings that need to be downloaded anyways to mmap, such that we do not have to load all of them at once.

**Comment by dirkweissenborn** [comment]
@pminervini @TimDettmers any updates on an SNLI model? Can someboday train one?

**Comment by dirkweissenborn** [comment]
@pminervini could you replace the old fastqa model with the newer version that uses memory maps? It is the same dropbox link.

**Comment by pminervini** [comment]
@dirkweissenborn done

**Comment by dirkweissenborn** [comment]
@pminervini sorry the model was only renewed now, can you do it again?
https://www.dropbox.com/s/wasdpmmpuywpdlm/fastqa.zip?dl=0

**Comment by pminervini** [comment]
@dirkweissenborn done!

**Comment by undwie** [comment]
@pminervini when you have time, could you also upload the memory map embeddings (see the doc on how to create them), and download them with the glove download script? (Maybe zipping and unzipping accordingly)? This would streamline the setup.

**Comment by pminervini** [comment]
@undwie sure!

**Comment by undwie** [comment]
Great! let me know when it's up!

**Comment by pminervini** [comment]
@undwie here you go: http://data.neuralnoise.com/jack/embeddings/

**Comment by undwie** [comment]
Most awesome!

**Comment by pminervini** [comment]
@undwie the different options for the pre-trained embeddings are now `word2vec`, `glove`, `memory_map_dir` - my understanding is that `memory_map_dir` is like `glove` but faster, is that right ?

**Comment by undwie** [comment]
Have a look at the documentation. Memory map loads embeddings lazily from
disk, only when needed, instead of pre-loading everything into memory.

**Comment by pminervini** [comment]
@undwie thank you - I've been going through the documentation, but I was thinking it was tied to `GloVe`.

**Comment by undwie** [comment]
No, you can load embeddings from any other format, and then save it in a memory map directory.

**Comment by riedelcastro** [comment]
@dirkweissenborn did you manage to train fastqa with the memory map files? For me things got much slower at training time, even though startup and memory footprint at test time is much better. But I am not sure right now if the slow training comes from the embeddings, or from other changes.

**Comment by dirkweissenborn** [comment]
@riedelcastro I did not train the model but only changed the configuration yaml in the shared resources to use mem_map. However, I found that training time was not affected by that much (10%), if at all. I have the mem map embeddings on SSD which should make a difference compared to an HDD. Anyway, I could try to provide a quick fix for that by caching embeddings in the input module. Over time, training should become faster then. What do you think?

**Comment by riedelcastro** [comment]
If it only hurts you by ~5%, this looks okay for now. Maybe something else is going on for me. On that note, I still haven't been able to reproduce your F1 results. I am always ending up somewhere at 72. @mitchelljeff, have you trained FastQA on squad with results in the F1=74% range?

**Comment by dirkweissenborn** [comment]
@riedelcastro can you bin/jack-eval.py the pre-trained model on the SQuAD dev set, just to be sure that it is really the training that is the problem for you?

Btw., I get similar results with my pyTorch implementation, so the results seem solid.

**Comment by riedelcastro** [comment]
Yes, I will do this. But in any case, the training does produce different intermediate outputs it seems.

**Comment by dirkweissenborn** [comment]
I never got TF to be completely deterministic, either. However, results shouldn't change too much.

**Comment by riedelcastro** [comment]
Yeah. It's weird: for me, I might have some variance, but I relatively consistently get around 72%.

**Comment by dirkweissenborn** [comment]
Did you ever train it on a GPU? I am really curious now...

**Comment by riedelcastro** [comment]
Not yet. Interestingly, in this run, after 10 iterations, I get to about 74. I guess it is indeed very non-deterministic. On the plus side, the memory map embeddings seem to "work" in the sense that you can train with them to get similar results. This wasn't properly tested before.
