### ISSUE TITLE
SotA configs + README updates to create SotA models

### ISSUE THREAD

**Issue by dirkweissenborn** [uclmr/jack#287]
The idea of the readme in my eyes is that someone clones the repo looks at the readme and can, with a couple of commands train a SotA model.

So, our configs should be the configs that can be used to create state-of-the-art results, not experimental. The README examples should show how to quickly train a state-of-the-art model, not serve as examples of how to train a small test model. We have that in the showcase notebook and our tests. For fastqa this has been done.

**Comment by dirkweissenborn** [comment]
Can somebody fix this? I think the README is rather important...

**Comment by riedelcastro** [comment]
I am hopelessly swamped right now. Maybe @mitchelljeff can help?

**Comment by dirkweissenborn** [comment]
#319
