### ISSUE TITLE
Fix Documentation

### ISSUE THREAD

**Issue by dirkweissenborn** [uclmr/jack#297]
I think the refactoring is now done, so we should fix our markdown documentation.

@undwie is hijacking this issue now! Generally, there are a two problems with the docs:

* Some things are out-of-date (e.g. names of classes, packages, folders etc.)
* Some things are redundant (e.g., https://github.com/uclmr/jack/blob/master/docs/How_to_install_and_run.md has a list of readers, and so does https://github.com/uclmr/jack/blob/master/docs/Model_Inventory.md)

Below I assign people to the individual files (roughly based on how worked on it before). Please check the files and fix the two issues above. That is, make sure any references to code and locations are consistent with the current state of jack. And make sure that when redundant information is minimised (for example by replacing the list of readers from the `How_to_install_and_run.md` file with a link to the `Model_Inventory.md` file.

- [x] @pminervini  https://github.com/uclmr/jack/blob/master/docs/Config.md
- [ ] @TimDettmers https://github.com/uclmr/jack/blob/master/docs/How_to_install_and_run.md? It looks fairly redundant   
- [x] @riedelcastro https://github.com/uclmr/jack/blob/master/docs/TensorPorts.md
- [x] @dirkweissenborn  https://github.com/uclmr/jack/blob/master/docs/Understanding_Jack_the_Reader.md
- [x] @undwie the rest

**Comment by riedelcastro** [comment]
Quick Ping to everyone else: this quick and easy to do. It will feel nice!

**Comment by undwie** [comment]
Guys, any progress on this?

**Comment by TimDettmers** [comment]
https://github.com/uclmr/jack/blob/master/docs/How_to_install_and_run.md is severely outdated and the handling is difficult (looking up paths to get things running and that sort of thing). It would be great if we had a simpler thing. We could have a Makefile which handles all of this.

For example `make SNLI` will download the SNLI data, transform it into jack format. We could even run a small model on SNLI. This makes it much easier for users to clone the jack repo and get started. People then could copy the commands from the SNLI to run a model and adjust them slightly (for example change reader, or embedding size etc).

I think this is the way to go. This also relates to #287. Do we currently have a mechanism to invoke configs? A simple `make run-SNLI-best` would be great to run the best SNLI that we have in jack. Or `make squad-bidaf` to run bidaf. This gets people started quickly.

What do you think?

**Comment by TimDettmers** [comment]
Other things need to be fixed because I can proceed with the two documents that were assigned to me. A list of models in a file should not be the only way to figure out what models you can run. This must be easier. See #309 for some suggestions.

**Comment by pminervini** [comment]
On it!

**Comment by riedelcastro** [comment]
Agree with all of the above, but I think it would be good to solve this now in the easiest possible way for v0.1, and then put this on the list for 0.2. We should avoid moving the goal post and release soon.

**Comment by TimDettmers** [comment]
In our group meeting, we decided to move along with this issue. I will fix the install document and we leave the model inventory as it is. We probably not update the testing documentation.

**Comment by TimDettmers** [comment]
I had another look at the `How_to_install_and_run.md` and to me, it seemed that most of it should be covered in the main `README.md` rather than there. Also in our group discussion, we decided to use config files by default rather than a Makefile for running models. We need to add a section how to use the config files, but other than that documentation seems to be fixed.

**Comment by riedelcastro** [comment]
Cool, so `How_to_install_and_run.md` is removed now?
