### ISSUE TITLE
installation for gpu

### ISSUE THREAD

**Issue by dirkweissenborn** [uclmr/jack#305]
it would be nice to have an setup procedure for cuda based installations. For instance, the tensorflow the requirements would have to change to `tensorflow-gpu`.

**Comment by pminervini** [comment]
I'll do something like https://github.com/tensorflow/tensor2tensor/blob/master/setup.py, so it will possible to do e.g. `pip install jack[gpu]`

**Comment by dirkweissenborn** [comment]
awesome

**Comment by TimDettmers** [comment]
It is currently not possible to install jack without TensorFlow CPU. If I only have TensorFlow GPU the install fails.

**Comment by pminervini** [comment]
This looks like the proper way of handling the issue:

https://github.com/tensorflow/tensor2tensor/blob/master/setup.py#L37

**Comment by pminervini** [comment]
https://github.com/uclmr/jack/pull/349
