### ISSUE TITLE
Bad user experience. Running models is difficult

### ISSUE THREAD

**Issue by TimDettmers** [uclmr/jack#307]
The current setup is very confusing. It took me 15 minutes to run a model on the original data. The current "Here is how you can run a model" uses standard configs on tests data. It is not obvious how to run models on real data, with real parameters. It is very confusing that there is `sacred` and we did not say anything about it in the `README.md` or anything else really. Currently, the user experience is terrible and as a new user I would drop Jack within 5 minutes.

I sketched a `Makefile` solution which might help people get up to speed. I will push this solution later. But I am unsure if it is the way to go.

**Comment by dirkweissenborn** [comment]
@TimDettmers this is not true for the fastqa model where it explains how to train a SotA model and shows how to load it. We have to include a pointer to the pretrained models #261  as well in the README such that a user can start right away.  

This is related to #287 and #297  where we discussed this already. Problem is that almost nobody really cared about the documentation yet.

**Comment by TimDettmers** [comment]
This works only for FastQA with a config file. Most models do not have config files. If I am a user I have no clue how to run any other model from the command line from here which makes me dependent on these configs files. For me, as a user, this would be very unattractive.

Interacting via command line is intuitive because people are used to doing this. The config should be a second, optional step which might be useful for SOTA results.

**Comment by dirkweissenborn** [comment]
I agree that we should show both types of interaction with jack, and maybe we should first show the how to train a model with all the configuration present in the configs and then show the shortcut by simply saying `with config=...`.

**Comment by dirkweissenborn** [comment]
@TimDettmers see new README. Is this better now?

**Comment by TimDettmers** [comment]
Thanks, Dirk. That's already much better. I think the only thing that we need now is also a way to give an overview of models and datasets and how to invoke them. For example, if I want to download SQuAD and run a model on SNLI, how long will it take to run it? Currently, for new users it would still require quite some item because they have to understand that (1) the description for SQuAD also is useful for other datasets (downloading), (2) they have to preprocess the data, which is not needed for SQuAD, this introduces quite some problems, and (3) they have to figure out paths and model names in order to run a model.

Given the current documentation a user would not be able to complete these steps (fails at (2)), and if the user does not fail he or she will still need more than 10 minutes to run a model on SNLI. We need to improve this.

**Comment by dirkweissenborn** [comment]
by preprocessing you mean conversion? If yes, this is not necessary for snli and squad style datasets (see README, there is no conversion), so users should not fail here.

Concerning datasets I think we should document SQuAD and SNLI for now in the README. The rest should be described in a separate doc.

Concerning models I think we should have allow for  `bin/jack-train.py --help`. This should print our models as categorized in our `implementations.py` file + your make file.

Concerning the fast user experience we should point the user to a pretrained model to start playing with it right away. We have that for fastqa, I will link it in the README.

**Comment by TimDettmers** [comment]
Ah, that makes sense. There is still a SNLI converter around and @pminervini and I just checked and the converter is not used in any code. He will delete that converter to not confuse anyone.

I think displaying models via `--help` is the cleanest solution. The `Makefile` could provide access to datasets that also entail preprocessing, that is non-SQuAD non-SNLI datasets currently.

A pretrained model is a big bonus for user experience. How large is the model though, the download could take a bit of time. Maybe a small model for SNLI would be helpful which can be downloaded quickly.

**Comment by dirkweissenborn** [comment]
I suggest that you try to download and run the fastqa model as described in the README. The problem there is still that embeddings are loaded very slowly, however, @riedelcastro has a fix with memory-maps. I (or hopefully @riedelcastro )  will try to integrate this soon.
 
I agree that a simple SNLI model would also be nice. However, I do not really feel responsible for the NLI part so it would be nice if somebody else could try to train an almost SotA model and host it.

**Comment by TimDettmers** [comment]
In our group meeting, we decided to go with config files and explain their usage in the README. We also decided that usability has low priority since it is currently just used internally. See #319
