### ISSUE TITLE
SQuAD data download does not work properly

### ISSUE THREAD

**Issue by TimDettmers** [uclmr/jack#308]
It copies it to the wrong directory (main directory). I do not know if there are other dependency problems.

**Comment by dirkweissenborn** [comment]
@TimDettmers I don't understand. Following the readme you download it in the SQuAD directory. However, I see your point. Feel free to change it such that you do not have to cd into the SQuAD directory first.

**Comment by TimDettmers** [comment]
Currently, it is download into the current directory rather than the `data/SQuAD` directory which make subsequent scripts fail.

**Comment by dirkweissenborn** [comment]
Please look at the README where it is stated that you have to cd into the SQuAD dir and download from there so it is not wrong, only inconvenient, we should change that. The same goes for GloVe for instance.
