### ISSUE TITLE
New pytest dependencies?

### ISSUE THREAD

**Issue by undwie** [uclmr/jack#311]
I have been running into problems with `pytest` because it now depends on `pytest-xdist` and `pytest-cov`. However, these are not in the dependencies? Somehow this works on wercker though. Am I missing something?

**Comment by pminervini** [comment]
Some dependencies were hardcoded into setup.py: the idea was that only `tests` should have depended on those, but this created confusion another time. Now all dependencies are in `requirements.txt`.

**Comment by undwie** [comment]
Great!
