### ISSUE TITLE
How to save and load models is unclear

### ISSUE THREAD

**Issue by TimDettmers** [uclmr/jack#321]
I took me 10 minutes to get a hint how to save models. This should be documented where you can find it. I could not find it in the documents and in the notebooks. I still do not full understand how to save/load models. I know it has to do with preferred metric and best score, but it is not clear where are models are saved, if it is automatic (seems so) etc. @dirkweissenborn I think you know how to do this, right? Can you please document that where one can find it.

**Comment by dirkweissenborn** [comment]
That is strange. The JTReader has only one method for that for saving called `store` and loading called `load_and_setup`. There is a convenience function in `jack/readers/implementations.py` called `reader_from_file(...)` where you just pass the `model_dir`. Readers are saved during training in `model_dir` as explained in the README.  [docs/Understanding_Jack_the_Reader.md](https://github.com/uclmr/jack/blob/master/docs/Understanding_Jack_the_Reader.md) misses an explanation for the JTReader though that explains this. However, there is a notebook called `Showcasing_Jack.ipynb` which explains all of this in detail.

**Comment by dirkweissenborn** [comment]
... and of course the README shows how to load a pretrained model. So I am a bit confused why you could not figure it out? Any suggestions how we can make this clearer in the documentation

**Comment by TimDettmers** [comment]
I did ctrl+f for "save" and could not find it. Then I skimmed all documents and I could not find it. Then I searched in the code and I could trace it back to the store call in the JTReader. Maybe we could create a FAQ or we could add some headings somewhere.

Currently, it is not clear where one would find which information.

**Comment by riedelcastro** [comment]
FWIW, I usually scan the API of an object, like the `JTReader` for what I can do with the object (such as saving, loading etc). I usually do that first, and if the docstring is good enough, that does it most of the time. I guess people just have different strategies here. Maybe it would help to have the generated API doc again? 

Maybe an explicit strategy would help, a la: to find information,

1) first check the README
2) if that doesn't work, read the `Showcasing ...` notebook
3) if that doesn't work, navigate through the API (either through the code, or through a generated API)

That's what I do with libraries I use (although usually there is a Manual instead of a `Showcasing...` notebook.

**Comment by dirkweissenborn** [comment]
well, store and save are kind of synonymous. Anyway, the showcase notebook even mentions "saving" as a keyword and we point to the notebooks right in the beginning of the README, so I am still a bit confused. Maybe you missed that particular notebook. So let us just point explicitly to this notebook in the README to show people how to interact with the readers and while pointing to it we mention that it shows how to create, save, load and setup readers, s.t. ctrl+f is successful right in the README. Feel free to adapt the README to your taste.

**Comment by dirkweissenborn** [comment]
@riedelcastro I think the easiest way to make sure the information is found is to properly link important keywords in the README with the corresponding documentation.

**Comment by TimDettmers** [comment]
@riedelcastro These strategies work. But if you use a software package, how often do you read entire non-searchable documents and notebooks just to figure out a functionality? Usually, you look these things up in an API documentation and we do not have that (or rather, its outdated). Maybe we should have that and integrate it into we reference things?

@dirkweissenborn I did not open the notebook. If I search the notebook file with grep I do not find "save". Notebooks are difficult to handle if you just want to look something up. Maybe we need an API documentation (we can also generate that) and integrate it into the current documentation.

**Comment by TimDettmers** [comment]
I guess one issue is also that I am using Vim. Sometimes the autocomplete does not work, and then it would be easier to just work with the software framework, but I do not think this is an excuse for not having good documentation for such kind of problems.

**Comment by dirkweissenborn** [comment]
Well, I really agree with @riedelcastro here that there are obviously different strategies which also depend on the used IDE. I disagree that notebooks are difficult to handle, I think they provide a very nice possibility for hands-on documentation.

I think I would read the basic documentation first to understand the basics of how a software works. Anyway, I understand that users that do not use more sophisticated code completion as in pycharm for instance will have trouble finding out what the methods of the created readers are without proper API doc. So we have to provide that. We also need explicit pointers in the readme for base functionality or at least in understanding jack. Additionally we should really encourage users to first go through the notebooks to get a feeling of jack and know the base functionality.

That said, I think it is great that we have some diversity here. So whoever finds it problematic to get to the proper documentation should extend it in a suitable way.

**Comment by dirkweissenborn** [comment]
closing this now
