### ISSUE TITLE
Jack install cannot use GPU

### ISSUE THREAD

**Issue by TimDettmers** [uclmr/jack#324]
Currently, Jack with GPU support can only be installed with some tricks. I removed the tensorflow requirement and only then I was able to install and run tensorflow-gpu. This is not intuitive.

One might be able to install jack with GPU support when one (1) install jack, (2) install tensorflow-gpu. But this does not work if one has tensorflow-gpu install before running (1). Then it will break the system and one has to manually delete packages from disk to make this work (or delete the requirement, tensorflow and then add tensorflow-gpu, like I did above ).

**Comment by pminervini** [comment]
Let's discuss this here (related issue): https://github.com/uclmr/jack/issues/305
