### ISSUE TITLE
overfitting is failing on werker but not locally

### ISSUE THREAD

**Issue by dirkweissenborn** [uclmr/jack#328]
any suggestions @pminervini ? 

In general these overfitting tests are kind of annoying because the models don't even overfit, on the contrary, the results seem to get worse over epochs. There is also a lot of variance in the results which makes frequent updates necessary whenever slight changes in the architecture/TF code occur. We should make these tests more stable.

**Comment by pminervini** [comment]
That's most likely because Wercker is using `TensorFlow 1.4.0` now!

**Comment by riedelcastro** [comment]
Agree with @pminervini. Also, this reminds me: we should fix our `requirements.txt` to make version numbers explicit. As it is, we can't guarantee that a pip install will always produce the same system.

**Comment by dirkweissenborn** [comment]
@pminervini @riedelcastro Don't get me wrong, I like the tests, I only think they are too brittle at the moment. There is just too much variance, maybe we should train on slightly more data for these tests. They are also not really overfitting tests, because the models do not overfit.
