### ISSUE TITLE
Rethinking `create_output` function in ModelModule

### ISSUE THREAD

**Issue by undwie** [uclmr/jack#331]
currently the way to create new `TFModelModules` is to implement `create_output` which has these variable argument lists depending on the port structure. In a way this is convenient, but also very opaque and magic. I am wondering if we should simply pass in the mapping from ports to tensors? When you implement this, you will then know that you need to look at the input ports to understand what this module receives, and this means, among other things, that you don't have to rewrite the documentation for inputs. 

For example, in `fastqa.py` the function `create_output` is annotated with the list of inputs and their dimensions, but this should already be defined in the port definitions. If the function would just accept a mapping from ports to tensors, it would be relatively clear what is happening and what the input is, without further documentation (which easily gets stale). 

Thoughts?

**Comment by dirkweissenborn** [comment]
I don't have a strong opinion on that. I think both is fine, but agree that a mapping from ports to tensors might be more intuitive and transparent when you start using jack.

**Comment by undwie** [comment]
The other benefit is that the method signatures don't need to be synchronized with the input ports (when they change), reducing likelihood of staleness.

**Comment by dirkweissenborn** [comment]
I don't think this is a valid point because if ports (not their order) change then you also need to account for that when fetching the tensors from the mapping in `create_output`. Anyway, although I think it makes you write a bit more boilerplate code, it might be easier to understand.

Reminds me that we should also rename the methods to something more intuitive, e.g., `compute_predictions` and `compute_losses`, or something like that.

**Comment by undwie** [comment]
I think it's a valid point because of course I will need to write
```python
def create_outputs(input_tensors:Mapping[Port,Tensor]):
   ...
   my_new_result = tf.whatever(input_tensors[Ports.whatever])
```
but that you have to do in the current implementation as well
```python
def create_outputs(..., whatever):
   ...
   my_new_result = tf.whatever(whatever)
```

**Comment by dirkweissenborn** [comment]
well ok, but if you change the code anyway, changing the signature is not terrible. However, I understand that it is easier the other way.

**Comment by undwie** [comment]
Okay, I also understand that it's not terrible :) But I take any reduction of redundancy I can get. But the main point is transparency for users, and avoidance of redundant documentation (which otherwise easily leads to conflicting documentation)

**Comment by dirkweissenborn** [comment]
@undwie so who is going to work on this?

**Comment by undwie** [comment]
Maybe @riedelcastro?

**Comment by dirkweissenborn** [comment]
@riedelcastro we could also think about making these functions static since states of model modules should be captured in the shared resources anyway.

**Comment by undwie** [comment]
And then adding a `shared_resources` parameter?

**Comment by dirkweissenborn** [comment]
it already is an argument

**Comment by riedelcastro** [comment]
How odd, given that it's part of the reader. I am happy with either:

* static method that gets the shared resources passed
* object method that accesses shared resources through `self.shared_resources`

Both doesn't make much sense.

**Comment by dirkweissenborn** [comment]
doing it statically can prevent people from giving the model module a state, such that people really use the ports and the shared resources properly.

**Comment by riedelcastro** [comment]
Good point

**Comment by dirkweissenborn** [comment]
any updates or expected updates on this @riedelcastro ?
