### ISSUE TITLE
Inconsistent/unclear configuration flags naming

### ISSUE THREAD

**Issue by pminervini** [uclmr/jack#351]
I was struggling to understand:
- How to save a model during training, and
- How to initialise the parameters from a checkpoint.

Turns out it's `reader_dir` and `pretrained_model` - thanks @dirkweissenborn !

Can we change it to `save_dir` and `load_dir`, or something along this line - for consistency and clarity ?

Let's just agree on the naming, then I'll handle it.

**Comment by dirkweissenborn** [comment]
I think `load_dir` is not a good idea here, because this is really just the path to a pretrained model. Maybe initialization_dir?

**Comment by pminervini** [comment]
`load_dir` sounds good to me, for the path to a pretrained model

**Comment by dirkweissenborn** [comment]
When you look at the configuration after training, I think this might be confusing, because of the duality of save_dir.

we should also change every falg with `_folder` to `_dir`.

**Comment by pminervini** [comment]
Why is it confusing ?

**Comment by dirkweissenborn** [comment]
Actually, it is really just a training FLAG anyway, so you are right. It might not make a difference after all. It is never used after training.
