### ISSUE TITLE
default save_dir in .yaml conf file

### ISSUE THREAD

**Issue by jg8610** [uclmr/jack#356]
In the section on training an NLI reader, you have two options that are implied to be equivalent, but they aren't equivalent: ./conf/nli/dam.yaml doesn't specify a save_dir and the default is null. 

My suggestion would be for the default save_dir to be './save_dir', so people running models on /.conf files don't get caught out.

Btw - the package is super useful!

Jonny

**Comment by dirkweissenborn** [comment]
hey johnny, thanks for the suggestion. I will set it to something like './saved_reader'.

**Comment by pminervini** [comment]
What if you don't want to save your model by default ?
