### ISSUE TITLE
Fix DAM and make ESIM as close to paper as possible

### ISSUE THREAD

**Issue by dirkweissenborn** [uclmr/jack#357]

**Comment by pminervini** [comment]
I've been working quite a lot for making those faithful to their respective papers:

https://github.com/uclmr/inferbeddings/blob/master/inferbeddings/nli/dam.py

https://github.com/uclmr/inferbeddings/blob/master/inferbeddings/nli/esim.py

**Comment by dirkweissenborn** [comment]
I know. DAM is mostly the same, ESIM is now a build by our modular model.

The problem with DAM is that you set the dropout rate to 0.8! You probably meant to set it to 0.2. Anyway, I will fix the NLI models, train and tweak them a little.

**Comment by dirkweissenborn** [comment]
results with the current implementations and configs are good enough for now
