### ISSUE TITLE
Test case failing because of SpaCy 1.9

### ISSUE THREAD

**Issue by pminervini** [uclmr/jack#368]
https://app.wercker.com/JohannesMaxWel/jack/runs

`jack` uses `spacy==1.9`, which in turn does `import pip`, which is an unsupported behavior: 

https://github.com/pypa/pip/issues/5081

The problem does not exist when using the latest `spacy`.

**Comment by pminervini** [comment]
I've just opened an issue on the SpaCy github: https://github.com/explosion/spaCy/issues/2112

**Comment by pminervini** [comment]
If we need to stick to the `1.x` branch of SpaCy, I'll commit a patch to their codebase after I'm done with the paper; otherwise we can simply switch to the latest version

**Comment by dirkweissenborn** [comment]
I would rather stick to 1.9 for now, because it is much faster on processing small documents which is more important at the moment. 2.0 was pretty bad, though I haven't checked recently. See #338

**Comment by pminervini** [comment]
Hey! I've temporarily switched to `spacy` (instead of `spacy==1.x`) to make `jack` work - now the tests turn out green.

There is a pull request to fix this on the `1.x` branch of `spacy` - I'll switch back to `1.x` when it's merged. Let's keep this issue open as a reminder!

**Comment by pminervini** [comment]
Fixed: https://github.com/explosion/spaCy/issues/2112
