### ISSUE TITLE
Fix dependency versions in requirements

### ISSUE THREAD

**Issue by leonweber** [uclmr/jack#383]
On a fresh install, jack refuses to run because of 
```bash
python3 bin/jack-train.py with config='./conf/qa/squad/fastqa.yaml'
Traceback (most recent call last):
  File "bin/jack-train.py", line 14, in <module>
    from sacred.arg_parser import parse_args
ImportError: cannot import name 'parse_args
```

This is most likely because ``sacred`` underwent an API change.
After ``pip install sacred==0.7.2`` everything works fine.

In order to prevent things like that, would it maybe be useful to pin the versions of the packages in ``requirements.txt``?

**Comment by dirkweissenborn** [comment]
Should be fixed now. Thanks :)
