### ISSUE TITLE
Training Script Bug

### ISSUE THREAD

**Issue by JohannesMaxWel** [uclmr/jack#386]
Training ESIM or DAM currently does not work.

Input: (without further modification to the default config)
> python3 bin/jack-train.py with config='./conf/nli/snli/esim.yaml'

yields this error
```
Traceback (most recent calls WITHOUT Sacred internals):
  File "bin/jack-train.py", line 112, in run
    vocab = Vocab(vocab=embeddings.vocabulary if vocab_from_embeddings and embeddings is not None else None)
TypeError: __init__() got an unexpected keyword argument 'vocab'
```

Same for DAM.

**Comment by dirkweissenborn** [comment]
Weird. Works normally for me on a fresh version of master. You sure you on the latest master without changes?
