### ISSUE TITLE
pretrained models - example not working

### ISSUE THREAD

**Issue by pgroth** [uclmr/jack#389]
I'm trying to just run a simple pretrained model following the instructions on the from the readme 

```
Traceback (most recent call last):
  File "jack_test.py", line 4, in <module>
    fastqa_reader = readers.reader_from_file("./fastqa_reader")
  File "/jackthereader/jack/jack/readers/implementations.py", line 60, in reader_from_file
    shared_resources.load(os.path.join(load_dir, "shared_resources"))
  File "/jackthereader/jack/jack/core/shared_resources.py", line 70, in load
    for f in os.listdir(path):
NotADirectoryError: [Errno 20] Not a directory: './fastqa_reader/shared_resources'
```
Looking instead the the director. shared_resources is indeed not a directory. There is a shared_resources_vocab directory. 

Any thoughts?

**Comment by dirkweissenborn** [comment]
Seems to be an old model. Can you try downloading the respective model from
the following link?

https://www.dropbox.com/sh/vnmc9pq4yrgl1sr/AAD7HVhGdpof2IgIifSZ6PEUa?dl=0

**Comment by pgroth** [comment]
Thanks that works!
